import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by Next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>{children}</body>
    </html>
  );
}
