import "./globals.css";
import Link from "next/link";
import Footer from "./layout/footer";
import Header from "./layout/header";

export const metadata = {
  title: "Home",
  description: "Generated by Next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
